# app/auth/dependencies.py
from fastapi import Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer
from app.auth.jwt import verify_token
from app.auth.azure_verify import verify_azure_token
from app.auth.service import auth_service

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/api/v1/auth/login")

async def get_current_user(token: str = Depends(oauth2_scheme)):
    """
    Universal authentication dependency.
    Accepts either:
      - JWT token generated by our app, or
      - Azure AD ID token (verified via JWKS)
    """

    # 1Try verifying local JWT (app-issued)
    payload = verify_token(token, expected_type="access")
    if payload:
        user_id = payload.get("sub")
        if not user_id:
            raise HTTPException(status_code=401, detail="Invalid JWT payload")

        user = await auth_service.get_user_by_id(user_id)
        if not user:
            raise HTTPException(status_code=401, detail="User not found")

        return user

    # 2Try verifying Azure AD ID token
    try:
        payload = await verify_azure_token(token)
        email = payload.get("email") or payload.get("preferred_username")

        if not email:
            raise HTTPException(status_code=401, detail="Azure token missing email")

        user = await auth_service.get_user_by_email_or_username(email, email)
        if not user:
            raise HTTPException(status_code=401, detail="User not found in local DB")

        return user

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Invalid token: {str(e)}",
        )
